### ISSUE TITLE
SSL Cert for paste.systems-emea.insight.com

### ISSUE THREAD

**Issue by maciejduk** [Insight-EMEA/ip-container-pwpush#142]
paste.systems-emea.insight.com

_Originally posted by @maciejduk in https://github.com/Insight-EMEA/ip-container-pwpush/issues/60#issuecomment-1398222417_

**Comment by maciejduk** [comment]
Waiting for Vlad to reply with signed Cert

**Comment by MatthewBieda** [comment]
https://paste.systems-emea.insight.com/
