### ISSUE TITLE
Create IDW Page for Pastebin

### ISSUE THREAD

**Issue by maciejduk** [Insight-EMEA/ip-container-pwpush#162]
Can you reach out to Vladimir Stojanovic and see if he has a template we need to deliver this content via?

**Comment by MatthewBieda** [comment]
Contacted him on Teams.

**Comment by MatthewBieda** [comment]
https://insightonlineeur.sharepoint.com/sites/tsg/SitePages/Insight-Secure-Pastebin.aspx

**Comment by maciejduk** [comment]
Add more info around
- [ ] why would one use it
- [ ] how is it better practise / more secure
- [ ] highlight use of API and the fact we use it in Automation
