### ISSUE TITLE
Update Favicon to Insight Branded

### ISSUE THREAD

**Issue by maciejduk** [Insight-EMEA/ip-container-pwpush#165]

**Comment by MatthewBieda** [comment]
Tested this locally on upstream branch but can't seem to actually get it working in the browser.

**Comment by MatthewBieda** [comment]
Think I have found the issue with this...

**Comment by maciejduk** [comment]
> Think I have found the issue with this...

Details? 😜

**Comment by MatthewBieda** [comment]
Just have to update files in some more places it looks like

**Comment by MatthewBieda** [comment]
Done.
