### ISSUE TITLE
Change App Name (page title)

### ISSUE THREAD

**Issue by maciejduk** [Insight-EMEA/ip-container-pwpush#60]
Can we update the name of the app to 
> Insight Secure Pastebin

This is due to some concerns from Security team. We can then work towards having `paste.systems-emea.insight.com`

**Comment by maciejduk** [comment]
paste.systems-emea.insight.com

**Comment by MatthewBieda** [comment]
![securepastebin](https://user-images.githubusercontent.com/63665300/213690919-df37a5b8-2e8b-4672-8de8-8aaceb4ea778.jpg)
